service: microservice-notification

frameworkVersion: '3'

plugins:
  - serverless-offline

provider:
  name: aws
  runtime: nodejs16.x
  region: eu-west-1
  memorySize: 256
  stage: ${opt:stage, 'dev'}
  profile: pdp-auction
  iamRoleStatements:
    - Effect: 'Allow'
      Action:
       - ses:SendEmail
      Resource: arn:aws:ses:*
  
functions:
  sendEmail:
    handler: src/handlers/sendEmail.handler